server:
  port: 3002
  servlet:
    context-path: /orchestrator

spring:
  application:
    name: Orchestrator

services:
  greeting-full-name:
    base-url: http://65.2.39.42:3003/greetingfullname
  greeting:
    base-url: http://65.2.39.42:3001/greeting